---
# follows the same parameter structure as the DB extractor configuration
cognite: # kwargs to pass to the CogniteClient, Environment variable format: ${ENVIRONMENT_VARIABLE}
  # host: https://${EXTPIPES_CDF_CLUSTER}.cognitedata.com/
  host: ${EXTPIPES_CDF_HOST}
  project: ${EXTPIPES_CDF_PROJECT}
  #
  # AAD IdP login credentials:
  #
  idp-authentication:
    client-id: ${EXTPIPES_IDP_CLIENT_ID}
    secret: ${EXTPIPES_IDP_CLIENT_SECRET}
    scopes:
        - ${EXTPIPES_IDP_SCOPES}
    token_url: ${EXTPIPES_IDP_TOKEN_URL}

logger:
  file:
    path: ./logs/extpipes-deploy.log
    level: INFO
  console:
    level: INFO

# extpipe-pattern only documentation atm
extpipe-pattern: '{source}:{short-name}:{rawtable-name}:{suffix}'

# can contain multiple contacts, can be overwritten on pipeline level
default-contacts:
  - name: Kevin Peng
    email: kevin.peng@accenture.com
    role: Bootcamp 43 Administrator
    send-notification: false

rawdbs:
    - rawdb-name: src:001:sap:db
      dataset-external-id: src:001:sap:ds
      short-name: sap
      rawtables:
        - rawtable-name: assets
          pipelines:
            - source: csv
              schedule: On trigger
              contacts:
                - name: Kevin Peng
                  email: kevin.peng@accenture.com
                  role: Bootcamp 43 Administrator
                  send-notification: false
    - rawdb-name: src:002:opcua:db
      dataset-external-id: src:002:opcua:ds
      short-name: opcua
      rawtables:
          - rawtable-name: datapoints
            pipelines:
                - source: csv
                  schedule: On trigger
                  contacts:
                    - name: Kevin Peng
                      email: kevin.peng@accenture.com
                      role: Bootcamp 43 Administrator
                      send-notification: false


